# -*- coding: utf-8 -*-
"""NDVI Data Cube Reconstruction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHLa6cnrB8dEFVlZ_tDAHkECeaHhXdkZ
"""

# ================================
# 1. Install packages
# ================================
!pip install -q xee geemap

# ================================
# 2. Initialize Earth Engine
# ================================
import ee
ee.Authenticate()

ee.Initialize(
    project='ee-lavibas23',
    opt_url='https://earthengine-highvolume.googleapis.com'
)

# ================================
# 3. Import libraries
# ================================
import geemap
import xarray as xr
import matplotlib.pyplot as plt

# ================================
# 4. Draw ROI interactively
# ================================
Map = geemap.Map(basemap='SATELLITE')
Map

# Get ROI
roi = Map.draw_last_feature.geometry()
roi

def add_ndvi(img):
    qa = img.select('QA_PIXEL')

    # Cloud mask bits
    cloud = qa.bitwiseAnd(1 << 3).neq(0)
    shadow = qa.bitwiseAnd(1 << 4).neq(0)
    mask = cloud.Or(shadow)

    # Scale reflectance
    sr = img.select('SR_B.*').multiply(2.75e-05).add(-0.2)

    # NDVI
    ndvi = sr.normalizedDifference(['SR_B5', 'SR_B4']).rename('ndvi')

    return ndvi.updateMask(mask.Not()).copyProperties(img, ['system:time_start'])


landsat = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")  # ✅ Landsat 8
    .filterBounds(roi)
    .filterDate('2023-01-01', '2024-12-31')
    .filter(ee.Filter.lt('CLOUD_COVER', 50))
    .map(add_ndvi)
)

print("Collection size:", landsat.size().getInfo())

Map.addLayer(landsat.median(), {'min': 0, 'max': 1}, 'NDVI median')
Map

ds = xr.open_dataset(
    landsat,
    engine='ee',
    scale=100,
    crs='EPSG:3857',
    geometry=roi
)

ds = ds.sortby('time')
ds

print(ds.dims)

# Original data (with clouds + gaps)
ds.ndvi.plot(
    x='X',
    y='Y',
    col='time',
    col_wrap=6,
    robust=True
)

# 1. Temporal interpolation (MOST IMPORTANT)
filled = ds.interpolate_na(dim='time', method='linear')

# 2. Spatial interpolation (FIXED DIM NAMES)
filled = filled.interpolate_na(dim='X', method='linear')
filled = filled.interpolate_na(dim='Y', method='linear')

filled.ndvi.plot(
    x='X',
    y='Y',
    col='time',
    col_wrap=6,
    robust=True
)

ndvi_smooth = filled.rolling(
    time=4,
    center=True,
    min_periods=1
).mean()

ndvi_smooth.ndvi.plot(
    x='X', y='Y',
    col='time',
    col_wrap=6,
    robust=True
)